package cn.glowd.proton.dal.mapper.manual;

import java.util.List;

import org.springframework.dao.DataAccessException;

import cn.glowd.proton.dal.model.HealthPackageDO;

/**
 * A dao interface provides methods to access database table <tt>health_package</tt>.
 *
 * This file is generated by <tt>proton dalgen</tt>, a DAL (Data Access Layer) code generation utility specially
 * developed for <tt>sample</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be OVERWRITTEN by someone else. To modify the
 * file, you should go to directory <tt>(project-home)/dalgen</tt>, and find the corresponding configuration file
 * (<tt>tables/health_package.xml</tt>). Modify the configuration file according to your needs, then run <tt>dalgen</tt>
 * to generate this file.
 *
 * @author glowd
 * @version $Id: description-java.vm,v 1.1 2018/01/11 07:34:20 glowd
 */
public interface ExtHealthPackageDOMapper {

    /**
     * Query DB table <tt>health_package</tt> for records.
     *
     * <p>
     * Description for this operation is<br>
     * <tt></tt>
     * <p>
     * The sql statement for this operation is <br>
     * <tt>select id, package_id, module_id, gmt_create, gmt_modified from health_package where moduleId= ?</tt>
     *
     * @param moduleId
     * @return HealthPackageDO
     * @throws DataAccessException
     */
    public List<HealthPackageDO> extSelectByModuleId(int moduleId);

}